project_id = "xbbnodpvfvxtbffziuvr"

[functions.vendx-pay-create-checkout]
verify_jwt = true

[functions.vendx-pay-webhook]
verify_jwt = false

[functions.vendx-pay-machine-auth]
verify_jwt = false

[functions.vendx-pay-session]
verify_jwt = false

[functions.vendx-pay-process]
verify_jwt = false

[functions.vendx-pay-balance]
verify_jwt = false

[functions.store-create-checkout]
verify_jwt = true

[functions.store-webhook]
verify_jwt = false

[functions.store-paypal-checkout]
verify_jwt = true

[functions.vendx-pay-paypal-checkout]
verify_jwt = true

[functions.paypal-capture]
verify_jwt = false

[functions.sync-payment-transactions]
verify_jwt = false

[functions.store-vendx-pay-checkout]
verify_jwt = false

[functions.store-refund-wallet]
verify_jwt = false
